USE [master]
GO
/****** Object:  Database [GestionAPP]    Script Date: 8/06/2022 15:59:28 ******/
CREATE DATABASE [GestionAPP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GestionAPP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GestionAPP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GestionAPP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GestionAPP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GestionAPP] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GestionAPP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GestionAPP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GestionAPP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GestionAPP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GestionAPP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GestionAPP] SET ARITHABORT OFF 
GO
ALTER DATABASE [GestionAPP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GestionAPP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GestionAPP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GestionAPP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GestionAPP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GestionAPP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GestionAPP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GestionAPP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GestionAPP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GestionAPP] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GestionAPP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GestionAPP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GestionAPP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GestionAPP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GestionAPP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GestionAPP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GestionAPP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GestionAPP] SET RECOVERY FULL 
GO
ALTER DATABASE [GestionAPP] SET  MULTI_USER 
GO
ALTER DATABASE [GestionAPP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GestionAPP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GestionAPP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GestionAPP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GestionAPP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GestionAPP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
