USE [master]
GO
/****** Object:  Database [GestionAPP]    Script Date: 8/06/2022 15:59:28 ******/
CREATE DATABASE [GestionAPP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GestionAPP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GestionAPP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GestionAPP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GestionAPP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GestionAPP] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GestionAPP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GestionAPP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GestionAPP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GestionAPP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GestionAPP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GestionAPP] SET ARITHABORT OFF 
GO
ALTER DATABASE [GestionAPP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GestionAPP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GestionAPP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GestionAPP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GestionAPP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GestionAPP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GestionAPP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GestionAPP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GestionAPP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GestionAPP] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GestionAPP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GestionAPP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GestionAPP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GestionAPP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GestionAPP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GestionAPP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GestionAPP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GestionAPP] SET RECOVERY FULL 
GO
ALTER DATABASE [GestionAPP] SET  MULTI_USER 
GO
ALTER DATABASE [GestionAPP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GestionAPP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GestionAPP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GestionAPP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GestionAPP] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GestionAPP] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GestionAPP', N'ON'
GO
ALTER DATABASE [GestionAPP] SET QUERY_STORE = OFF
GO
USE [GestionAPP]
GO
/****** Object:  Table [dbo].[categoria]    Script Date: 8/06/2022 15:59:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[categoria](
	[Id_categoria] [int] NOT NULL,
	[nombre_categoria] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_categoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[documentos]    Script Date: 8/06/2022 15:59:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[documentos](
	[id_documento] [int] NOT NULL,
	[Id_usuario] [int] NOT NULL,
	[nombre_documento] [varchar](30) NOT NULL,
	[documento] [varchar](20) NOT NULL,
	[fechacreacion] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_documento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[pagos]    Script Date: 8/06/2022 15:59:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[pagos](
	[Id_pago] [int] IDENTITY(1,1) NOT NULL,
	[Id_usuario] [int] NOT NULL,
	[id_categoria] [int] NOT NULL,
	[nombre_pago] [varchar](30) NOT NULL,
	[fechaingreso] [varchar](20) NOT NULL,
	[fechapago] [varchar](20) NOT NULL,
	[alerta] [int] NOT NULL,
	[estado] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_pago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[usuario]    Script Date: 8/06/2022 15:59:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuario](
	[Id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[usuario] [varchar](20) NOT NULL,
	[Nombre] [varchar](20) NOT NULL,
	[Apellido_paterno] [varchar](20) NOT NULL,
	[Apellido_materno] [varchar](20) NOT NULL,
	[Correo] [varchar](50) NULL,
	[Fecha_nacimiento] [char](8) NULL,
	[password] [varchar](20) NULL,
	[estado] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[documentos]  WITH CHECK ADD  CONSTRAINT [fk_usuariodoc] FOREIGN KEY([Id_usuario])
REFERENCES [dbo].[usuario] ([Id_usuario])
GO
ALTER TABLE [dbo].[documentos] CHECK CONSTRAINT [fk_usuariodoc]
GO
ALTER TABLE [dbo].[pagos]  WITH CHECK ADD  CONSTRAINT [fk_categoria] FOREIGN KEY([Id_usuario])
REFERENCES [dbo].[categoria] ([Id_categoria])
GO
ALTER TABLE [dbo].[pagos] CHECK CONSTRAINT [fk_categoria]
GO
ALTER TABLE [dbo].[pagos]  WITH CHECK ADD  CONSTRAINT [fk_usuario] FOREIGN KEY([Id_usuario])
REFERENCES [dbo].[usuario] ([Id_usuario])
GO
ALTER TABLE [dbo].[pagos] CHECK CONSTRAINT [fk_usuario]
GO
USE [master]
GO
ALTER DATABASE [GestionAPP] SET  READ_WRITE 
GO
